replab/replab

- docs/docs/scope.md
Provides a quick reference to have a clue whether some general element can be expected to be supported by the library or not.
Also a potential source of ideas for summer projects :-)
> Added documentation file to keep track of the library scope from a user perspective

- src/+replab/+directproduct/OfCompactGroups.m
- src/+replab/+quantum/GHZ.m
- src/+replab/+quantum/GHZBase.m
- src/+replab/+quantum/GeneralizedPauli.m
- src/+replab/+signed/PermutationGroup.m
- src/+replab/CommutantVar.m
- src/+replab/OrthogonalGroup.m
- src/+replab/PermutationGroup.m
- src/+replab/UnitaryGroup.m
- tests/Bug12Test.m
- tests/Bug14Test.m
- tests/Bug68Test.m
- tests/CommutantProjectTest.m
- tests/ComplexReflectionGroupTest.m
- tests/QuantumTest.m
- tests/RepresentationsTest.m
- tests/SubRepNUTest.m
> Rename naturalRep in definingRep

- docs/docs/api_documentation_style.md
adding non-capitalization of names + full class structure for See also section
> Further doc for #116 - following PR #120

- docs/docs/api_documentation_style.md
Correcting indentation for proper markdown interpretation
> correct markdown formatting error

- src/+replab/+irreducible/decompositionUsingSplit.m
We already merge a quick fix for #166. This already deals with the problem for current purposes. We can look for a more global and optimized solution when we decide to deal with performance issues.
> small optimization

- src/+replab/+lobster/CallNode.m
- src/+replab/+lobster/Compiler.m
- src/+replab/+lobster/ElseNode.m
- src/+replab/+lobster/FRAGMENT_TYPE.m
- src/+replab/+lobster/ForNode.m
- src/+replab/+lobster/Fragment.m
- src/+replab/+lobster/IfNode.m
- src/+replab/+lobster/LICENSE.md
- src/+replab/+lobster/Node.m
- src/+replab/+lobster/README.md
- src/+replab/+lobster/Root.m
- src/+replab/+lobster/Template.m
- src/+replab/+lobster/TextNode.m
- src/+replab/+lobster/VarNode.m
- src/+replab/+lobster/dump_template_ast.m
- src/+replab/+lobster/eval_with_context.m
- src/+replab/+lobster/print_node.m
- tests/lobster/IfTest.m
- tests/lobster/TemplateTest.m
... from https://github.com/comkieffer/Lobster-Templates
Corrected small bugs (Else node creation, missing code fragments in tests and README.md)
Adapted code to RepLAB conventions, including the use of MOxUnit
> Integrated the Lobster Template engine

- src/+replab/+infra/indent.m
- src/+replab/Domain.m
- src/+replab/Str.m
- src/replab_runtests.m
Standardizes doctests on the Matlab output
> Fixes #187

- sphinx/development/organization.rst
- sphinx/tutorials/installation.rst
- src/+replab/+bsgs/Chain.m
- src/+replab/+infra/+repl/ProgressBar.m
- src/+replab/+infra/+repl/formatHelp.m
- src/+replab/+infra/Class.m
- src/+replab/+infra/ClassData.m
- src/+replab/+rep/DirectSumRep.m
- src/+replab/+rep/TensorRep.m
- src/+replab/+rep/assertCompatibleFactors.m
- src/+replab/CompactGroup.m
- src/+replab/Context.m
- src/+replab/Equivariant.m
- src/+replab/Monoid.m
- src/+replab/NiceFiniteGroup.m
- src/+replab/SubRep.m
> Escaping Sphinx `*` characters

- src/+replab/Laws.m
Is it correct to add this line?
> 'testNames' undefined

- src/+replab/+init/initHelp.m
> correct help folder name

- src/+replab/+bsgs/Chain.m
This enables us to compute quickly a verified BSGS chain if the order is small. We'll use that to attempt automatic group recognition when displaying a group.
> Implementation of deterministic Schreier-Sims

- src/+replab/+bsgs/TrivialGroup.m
- src/+replab/FiniteFPGroup.m
- src/+replab/FiniteGroup.m
- src/+replab/HarmonizedIsotypic.m
- src/+replab/Irreducible.m
- src/+replab/NiceFiniteGroup.m
- src/+replab/NiceFiniteSubgroup.m
- src/+replab/Obj.m
- src/+replab/PermutationGroup.m
- src/+replab/Rep.m
- src/+replab/SignedPermutationGroup.m
- src/+replab/SignedSymmetricGroup.m
- src/+replab/SymmetricGroup.m
> Implement a property cache

- src/+replab/+str/align.m
> align uses Table

- src/+replab/+bsgs/ChainWithWords.m
- src/+replab/+nfg/AbstractGroupIsomorphism.m
- src/+replab/+nfg/AbstractGroupIsomorphismChain.m
- src/+replab/+nfg/AbstractGroupIsomorphismEnumeration.m
- src/+replab/AbstractGroup.m
- src/+replab/FiniteGroup.m
- src/+replab/FiniteIsomorphismLaws.m
- src/+replab/Obj.m
- src/+replab/PermutationGroup.m
This implements fully the Minkwitz factorization algorithm. We recover similar (but not exact) results as in the Table 1 of
`T. Minkwitz, "An Algorithm for Solving the Factorization Problem in Permutation Groups,", Journal of Symbolic Computation, vol. 26, no. 1, pp. 89–95, Jul. 1998`
> Minkwitz word factorization algorithm

- src/+replab/+indf/FiniteGroupIndexedFamily.m
- src/+replab/+lambda/IndexedFamily.m
- src/+replab/+perm/Set.m
- src/+replab/+perm/conjugacyClassesByRandomSearch.m
- src/+replab/CharacterTable.m
- src/+replab/ConjugacyClass.m
- src/+replab/DoubleCoset.m
- src/+replab/FiniteGroupLaws.m
- src/+replab/FiniteSet.m
- src/+replab/IndexedFamily.m
- src/+replab/IndexedFamilyLaws.m
- src/+replab/LeftCoset.m
- src/+replab/LeftCosets.m
- src/+replab/NormalCoset.m
- src/+replab/NormalCosets.m
- src/+replab/RightCoset.m
- src/+replab/RightCosets.m
- tests/replab/ConjugacyClassTest.m
... as Matlab class `size(X)` as part of the `isscalar` function and so on.
> Rename FiniteSet.size to nElements

- src/+replab/+infra/+repl/callOriginalHelp.m
- src/help_overload/help.m
> support printing of help by matlab and no argument for help

- src/+replab/+bsgs/MatrixAutomorphism.m
- src/+replab/PermutationGroup.m
Note: this may overlap with the graph automorphism search developed by @jdbancal !
Should we merge the two in the future, or simply cross-check them using both implementations?
> Computation of matrix stabilizers

- src/+replab/+atlas/Standard.m
- src/+replab/AbstractGroup.m
- src/+replab/DihedralGroup.m
- src/+replab/KleinFourGroup.m
Changes to `+replab.atlas/Standard` and `+replab/Dihedral_group` to incorporate Klein four-group as `replab.DihedralGroup(2)`
> Added Klein four-group as a function and to Dihedral group

- src/+replab/FiniteGroup.m
- tests/issues/Issue420Test.m
> Fix issue #420

- src/+replab/+bsgs/ChainWithWords.m
- src/+replab/+mrp/Factorization.m
- src/+replab/+mrp/FactorizationChain.m
- src/+replab/+mrp/FactorizationEnumeration.m
- src/+replab/+mrp/FactorizationTrivial.m
- src/+replab/+mrp/inverseIndices.m
- src/+replab/PermutationGroup.m
* Optionally perform factorization without using generator inverses
* Flexible choice of generating set in the internal Factorization class
> More flexible factorization of finite group elements

- src/+replab/Partition.m
Removing some code which can take up significant amount of memory, and which is done twice
> This is already done later

- external/modules.ini
- sphinx/development/organization.rst
Updating MOxUnit submodule and documenting submodule update procedure
> Document submodules

- src/+replab/+cvar/symmetrizeIndexMatrix.m
> Oh octave, oh octave!

- src/+replab/+equi/Equivariant_forCompactGroup.m
- src/+replab/+laws/RepLaws.m
- src/+replab/+prods/WreathProductGroup_Rep.m
- src/+replab/+prods/WreathProductGroup_compact.m
- src/+replab/+rep/ComplexifiedRep.m
- src/+replab/+rep/CompositionRep.m
- src/+replab/+rep/DerivedRep.m
- src/+replab/+rep/DirectSumRep.m
- src/+replab/+rep/IndexRelabelingRep.m
- src/+replab/+rep/RepByImages_monomial.m
- src/+replab/+rep/RestrictionRep.m
- src/+replab/+rep/TensorRep.m
- src/+replab/+rep/TrivialRep.m
- src/+replab/Rep.m
- tests/replab/rep/IndexRelabelingRepTest.m
This speeds up equivariant computations and iterative methods as the representation image does not need to be computed, only its action.
> Added optimized actions of representations on matrices

- src/+replab/+infra/+repl/ProgressBar.m
- src/+replab/Isomorphism.m
Progress fluctuating (i.e. sometimes going back a little bit) should not affect the progress bar significantly.
> Robust progress bar

- src/+replab/Equivariant.m
- src/+replab/Irreducible.m
- src/+replab/IrreducibleEquivariant.m
- src/+replab/Isotypic.m
- src/+replab/IsotypicEquivariant.m
- src/+replab/Rep.m
- src/+replab/SubEquivariant.m
- src/+replab/SubRep.m
It is replaced by `.sesquilinearInvariant`
> Remove `Rep.hermitianInvariant`

- src/+replab/+equi/Equivariant_forCompactGroup.m
- src/+replab/+equi/Equivariant_forFiniteGroup_explicitSum.m
- src/+replab/+equi/Equivariant_forFiniteGroup_relativeReynolds.m
- src/+replab/+equi/Equivariant_forMonomialRep.m
- src/+replab/Equivariant.m
- src/+replab/IrreducibleEquivariant.m
- src/+replab/IsotypicEquivariant.m
- src/+replab/Rep.m
- src/+replab/SubEquivariant.m
- src/+replab/SubRep.m
This adds support for symmetric/Hermitian spaces
> Richer equivariant spaces

- replab_config.m
- src/+replab/+infra/+doctests/DocTestStatement.m
- src/+replab/+util/bitrol32.m
- src/+replab/+util/md5.m
- src/+replab/+util/md5_plain.m
- src/+replab/Character.m
- src/+replab/CharacterTable.m
- src/+replab/ComplexCharacterTable.m
- src/+replab/Irreducible.m
- src/+replab/PermutationGroup.m
- src/+replab/SignedPermutationGroup.m
- src/+replab/SymmetricGroup.m
- src/+replab/cyclotomic.m
- testmd5.m
- tests/replab/IrreducibleTest.m
... so that tests can be run in an environment without Java
> Support for skipping tests that require JVM
