replab/replab

- .gitmodules
- .travis.yml
- replab_addpaths.m
- replab_runtests.m
- tests/codeCoverageHelperFunction.m
Taking advantage of a bug fix in MOxUnit allowing multiple exclusion folders for code covering, to simplify the test structure.
Left out the question of why BSGS code doesn't appear in coverage report yet.
> Cleaner test structure

- tests/CommutantVar/sizeTest.m
Octave has some trouble with anonymous functions using local class objects, currently we avoid problematic tests in this case
> avoid one octave bug

- src/+replab/IrreducibleCommutant.m
- src/+replab/IrreducibleRep.m
- src/+replab/Isotypic.m
- tests/CommutantProjectTest.m
This implements projection in the commutant, after the decomposition into irreducibles has been done.
```matlab
C = replab.S(20).cyclicSubgroup;
rep = C.naturalRep;
X = randn(rep.dimension, rep.dimension);
I = rep.decomposition;
X1 = I.asConjugateRep.commutant.project(X); % original representation with change of basis
X2 = I.asRep.commutant.project(X1); % synthetic representation from irreducible decomposition
assert(norm(X1 - X2) < replab.Settings.doubleEigTol);
```
@jdbancal We need something similar for `CommutantVar`. Note the basis for quaternion encoding in the commutant differs from the representation quaternion encoding by signs. No idea why now.
> Fast projection in the commutant

- replab_easy_install.m
Added a helper script that downloads the most up to date dependencies from a separate branch (`externals`, containing a single ZIP file named `replab_externals.zip`) on the GitHub repository, and unzips the missing dependencies in `external`.
The script lacks better error handling, and detection of Git submodules (in which case, the user should run the `git submodule update` command instead).
Tested with Octave and Matlab.
> (WIP) Easy installation script for external modules

- docs/index.md
The doc only mentioned the two original contributors to this project. Now all contributors are acknowledged.
> Adding a reference to the list of all github contributors

- src/+replab/CommutantVar.m
When requesting only few elements of the SDP matrix, it is not necessary to compute the full product U*M*U': only specific lines of U are needed
> subsref computes smaller products

- src/replab_runtests.m
I added a list of files to exclude from the code coverage. Currently, due to https://github.com/MOcov/MOcov/issues/16, this can only be done through generic file patterns (which are applied to all subfolders). Hence we need to have quite specific file patterns (cannot use `src/+replab/file.m` to exclude a single file for example)
> added excluding file pattern for code coverage

- sphinx/tutorials/installation.rst
- src/replab_release.m
@jdbancal I updated the Git installation instructions so that `replab_release` can work correctly, ignored the compiled files in the SDPT3 repository (it should have a `.gitignore` directive for that, but that repository is not under our control). Pinging you so that you can update your local config.
> Installation instructions (ignore SDPT3 untracked files)

- src/+replab/+infra/+repl/seconds2human.m
This avoids a warning on some Matlab versions
> Replace nargchk by explicit test

- src/+replab/+bsgs/Chain.m
We handle base changes quite inefficiently. This changes the `baseChange` procedure by handling redundant base points directly.
> Faster base changes

- src/+replab/+bsgs/Chain.m
- src/+replab/+bsgs/ChainWithImages.m
- src/+replab/+nfg/conjugacyClassesByOrbits.m
- src/+replab/+util/findRowInMatrix.m
- src/+replab/PermutationGroupLeftCosets.m
We use two strategies.
1. In general, `ismember(A, B, 'rows')` is extremely slow. We introduce a function `replab.util.findRowInMatrix` that is much faster.
2. When the expected list of elements is large, as in the computation for conjugacy classes, we use a simple multiplicative hash of the permutation -- that was already done. However, the search in the hash vector scales in `O(n)`. Now, we instead sort this hash vector once, and we perform lookups using a binary search. For the binary search, we use the Matlab builtin `ismembc2`. We keep a slow path available for Octave as Octave doesn't have the `ismembc2` function.
> Faster permutation search

- src/+replab/GeneralLinearGroup.m
- src/+replab/GeneralLinearGroupWithInverses.m
- src/+replab/OrthogonalGroup.m
- src/+replab/RepByImages.m
- src/+replab/SubRep.m
- src/+replab/UnitaryGroup.m
- tests/replab/RepByImagesTest.m
> RepByImages preserves sparsity by having sparse identity matrix

- src/help_overload/help.m
Fixes #312
The rationale behind *not* handling `replab_init` using our own framework: it would introduce different root folders for the code base parsing, and I'm not prepared to do that.
The alternative is to "fake" the presence of a `replab_init.m` file in the `src/` folder, but that may introduce problems when there are parse errors and we provide the path to the file.
> Let MATLAB original help function handle the replab_init argument

- src/+replab/+indf/FiniteGroupIndexedFamily.m
- src/+replab/+perm/Set.m
- tests/replab/perm/SetTest.m
We introduce a set of permutations backed by an ordered hash structure.
This lifts the work done in `FiniteGroupIndexedFamily` but provides additional methods.
> Permutation sets

- src/+replab/Action.m
- src/+replab/Domain.m
- src/+replab/FiniteFPGroup.m
- src/+replab/FiniteGroup.m
- src/+replab/FiniteIsomorphism.m
- src/+replab/FiniteIsomorphismLaws.m
- src/+replab/FiniteMorphism.m
- src/+replab/FreeGroup.m
- src/+replab/Group.m
- src/+replab/HarmonizedIsotypic.m
- src/+replab/IndexedFamily.m
- src/+replab/Irreducible.m
- src/+replab/Isotypic.m
- src/+replab/LeftCosets.m
- src/+replab/Monoid.m
- src/+replab/Obj.m
- src/+replab/Partition.m
- src/+replab/PermutationGroup.m
- src/+replab/Rep.m
- src/+replab/RightCosets.m
- src/+replab/SignedPermutationGroup.m
- src/+replab/SubRep.m
... and default implementations for all RepLAB objects with laws.
Fixes #305
> Added `replab.Obj.laws` method that returns the relevant laws

- src/+replab/+bsgs/Backtrack.m
- src/+replab/+bsgs/Centralizer.m
- src/+replab/+bsgs/Chain.m
We compute the base changes involving redundant base points implicitly during `generate`. This speeds up the process immensely.
> Optimize backtrack searches

- src/+replab/+bsgs/ConjugacyClasses.m
- src/+replab/+perm/conjugacyClassesByRandomSearch.m
- src/+replab/CharacterTable.m
- src/+replab/ConjugacyClass.m
- src/+replab/FiniteGroup.m
- src/+replab/FiniteSet.m
- src/+replab/PermutationGroup.m
- test_conjugacy.m
- tests/replab/bsgs/ConjugacyClassesTest.m
We construct conjugacy classes by looking for their minimal representative under lexicographic ordering.
> Conjugacy classes have canonical representatives

- src/+replab/+compat/uniqueStable.m
- src/+replab/+directproduct/OfFiniteGroups.m
- src/+replab/+infra/+repl/formatHelp.m
- src/+replab/+infra/+repl/help_full_class.liquid
- src/+replab/+infra/+sphinx/class.liquid
- src/+replab/+infra/Class.m
- src/+replab/+infra/ClassData.m
- src/+replab/+infra/Declarations.m
- src/+replab/+infra/MethodGroup.m
- src/+replab/+semidirectproduct/OfFiniteGroups.m
- src/+replab/AbstractGroup.m
- src/+replab/ConjugacyClass.m
- src/+replab/Domain.m
- src/+replab/FiniteGroup.m
- src/+replab/FiniteSet.m
- src/+replab/LeftCoset.m
- src/+replab/Monoid.m
- src/+replab/NiceFiniteGroup.m
- src/+replab/NormalCoset.m
- src/+replab/Obj.m
- src/+replab/PermutationGroup.m
- src/+replab/RightCoset.m
- src/+replab/SignedSymmetricGroup.m
- src/+replab/Str.m
- src/+replab/SymmetricGroup.m
This needs documentation.
In particular, document that:
- `(Abstract)` is stripped from group names
- `Implementations` is removed as it pertains to implementations of abstract methods
We also need to use the method groups when generating the Sphinx documentation.
> Support for method groups

- src/+replab/SymmetricGroup.m
as we can use pretty large symmetric groups for the `type`.
> Do not precompute the SymmetricGroup order

- src/+replab/+mrp/FindMorphisms.m
- src/+replab/+sym/CGTest.m
- src/+replab/FiniteGroup.m
- src/+replab/FiniteMorphism.m
This implements the algorithm EPIMORPHISMS described in Holt, Handbook of Computational Group Theory.
> Find (iso/epi)morphisms between groups

- replab_config.m
- replab_init.m
- src/+replab/+init/existingSdpSolver.m
- src/+replab/+init/sdpt3.m
SDP solver setup. The idea is to make sure we have a working SDP solver to pass the tests in `replab_runtests`. This should work ideally:
- whether the user already has a good solver in his path or not (in which case use it to avoid altering his setup), 
- even if the user's solver has no valid license anymore (in this case we use our embedded solver)
- if the user doesn't know what an SDP solver is of course
> Separate checks for some good SDP solver, and SDPT3 (if needed)

- src/+replab/+rep/ComplexifiedRep.m
- src/+replab/+rep/DefiningRep.m
- src/+replab/+rep/DerivedRep.m
- src/+replab/+rep/DirectSumRep.m
- src/+replab/+rep/TensorRep.m
- src/+replab/+rep/TrivialRep.m
- src/+replab/Isotypic.m
- src/+replab/Rep.m
This restores an old RepLAB capability: the use of coarse block structure already present in the representations to decompose.
> Use coarse block structure in decomposition

- src/+replab/+bsgs/LexMin.m
- src/+replab/PermutationGroup.m
- tests/replab/LexMinTest.m
Implements a method `vectorFindLexMinimal` on `PermutationGroup` to find a canonical representative of a vector under permutation of its coefficients by a permutation group.
Fixes #474
> Minimal lexicographic representative under a permutation group

- src/+replab/+init/initHelp.m
> On windows, `fullfile` replaces `/` by `\`

- src/+replab/+rep/repByImages.m
- src/+replab/+str/CyclotomicTable.m
- src/+replab/Character.m
- src/+replab/Rep.m
- src/+replab/cyclotomic.m
- tests/replab/RepByImagesTest.m
Goal: every method/function that takes cyclotomic arguments can take heterogeneous cell arrays instead, and their elements are converted to cyclotomic numbers.
First step:
Second step: enable support of extended syntax everywhere
> Easier API for use of cyclotomics

- src/+replab/+bsgs/ChainWithWords.m
- src/+replab/+laws/CosetLaws.m
- src/+replab/+laws/FiniteSetLaws.m
- src/+replab/+laws/LeftCosetsLaws.m
- src/+replab/+laws/RightCosetsLaws.m
- src/+replab/+mrp/Factorization.m
- src/+replab/+mrp/FactorizationChain.m
- src/+replab/+mrp/FactorizationEnumeration.m
- src/+replab/Coset.m
- src/+replab/LeftCoset.m
- src/+replab/NormalCoset.m
- src/+replab/PermutationGroup.m
- src/+replab/RightCoset.m
- tests/replab/bsgs/ChainWithWordsTest.m
Adding a method to `replab.bsgs.ChainWithWords` to words that belong to a coset, without necessarily correspond to the nominal coset representative. The idea is that some elements of a coset might be much easier to express than others, and we have no guarantee on the properties of the chosen representative. The method comes with no guarantee of minimality for the word length, but at least attempts to choose the element of the coset according to this purpose.
The implementation for `RightCoset` seems incomplete at the moment (currently same method, with the flag `isRightCoset`): the words provided don't produce an element of the coset (although the permutation does belong to the coset...) I must have missed one or two inversions somewhere, but can't point it down. Any idea where this might …
> Coset word

- src/+replab/Irreducible.m
- src/+replab/IrreducibleEquivariant.m
- src/+replab/equivar.m
This starts the work on a generic equivariant sdpvar implementation.
Currently, `IrreducibleEquivariant` has some bugs that need to be squashed before continuing.
```
rep = replab.S(3).naturalRep.tensorPower(2)
rep = 
Orthogonal tensor representation
dimension: 9
divisionAlgebraName: []
field: 'R'
group: Symmetric group acting on 3 elements
isUnitary: true
factor(1): Orthogonal reducible representation
factor(2): Orthogonal reducible representation
>> rep.decomposition.sesquilinearInvariant
ans = 
9 x 9 equivariant matrices over R
blockColSize: [2, 1, 6]
blockRowSize: [2, 1, 6]
blocks: 3 x 3 cell
field: 'R'
group: Symmetric group acting on 3 elements
nC: 9
nR: 9
nonZeroBlocks: [true, true, false; true, true, false; false, false, true]
parent: 9 x 9 equivariant matrices over R
repC: …
```
> [WIP] equivar

- src/+replab/cyclotomic.m
The method `a + b` where `a` is a cyclotomic and `b` a rational number was incorrect. This is fixed.
Now pretty-prints quadratic extensions using the `sqrt` syntax.
> Better display for cyclotomics (and bugfix)

- CODE_OF_CONDUCT.md
We have a code of conduct (c.f. website), but it does not appear on the gihub side. Adding here a dedicated file following github's expected filename. @denisrosset feel free to merge if that is fine with you!
> Adding our code of conduct in a dedicated file

- replab_init.m
- src/+replab/+infra/crawl.m
- src/canary/replab_canary.m
Detects and errors during replab_init if user added RepLAB subfolders to the path, through the use of a canary file that should not be visible
> feat: detection of unwanted RepLAB folders in the path

- sphinx/_static/js/collapse_helper.js
@jdbancal Making a PR as "collapse_helper.js" should be corrected in all Sphinx repositories
> Fix typo collapse_helper.js

- src/+replab/PermutationGroup.m
- tests/issues/Issue635Test.m
The method PermutationGroup.normalClosure did not return a correct set of generators.
It did omit the generators of the object of which we construct the closure.
We fix the issue and add a test.
Fixes #635
> fix: correct PermutationGroup.normalClosure
